Update patch set 5
Patch Set 5:

Looks like this change broke one of the Google Nest product builds, 
we are getting:

src/third_party/lss/linux_syscall_support.h:3682:7: error: use of undeclared identifier '__NR_ssize_t'

Patch-set: 5
CC: Gerrit User 1390420 <1390420@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>